#!/bin/bash

echo "##############################"
echo "# bijwerken repositories en bijwerken OS #"
echo "##############################"

apt-get update
apt-get upgrade -y

echo "##########################"
echo "# downloaden backup programma #"
echo "##########################"

cd /usr/local/bin
git clone https://github.com/kveys/backup.git
rm -rf /usr/local/bin/backup/.git

echo "#####################"
echo "#downloaden Linux scripts #"
echo "#####################"

cd /tmp
git clone https://github.com/kveys/linux.git
mv /tmp/linux/modfinder.sh /usr/local/bin
rm -rf /tmp/linux


echo "##############"
echo "#installatie Nginx #"
echo "##############"
apt-get install nginx -y

echo "################"
echo "#firewall aanpassen #"
echo "################"
ufw allow 'Nginx Full'

echo "##############"
echo "# PHP installeren  #"
echo "##############"

apt-get install software-properties-common -y
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php7.2-fpm php7.2-common php7.2-mbstring php7.2-xmlrpc php7.2-sqlite3 php7.2-soap php7.2-gd php7.2-xml php7.2-cli php7.2-tidy php7.2-intl php7.2-json php7.2-curl php7.2-zip -y

echo "###################"
echo "#downloaden PHP repo  #"
echo "###################"

cd /tmp
git clone https://github.com/kveys/php.git
mv /tmp/php/php.ini /etc/php/7.2/fpm
rm -rf /tmp/php

echo "###############"
echo "#Nginx herstarten  #"
echo "###############"
systemctl restart nginx

echo "#########################"
echo "#downloaden Dokuwiki software #"
echo "#########################"

cd /var/www/html/
git clone --branch stable https://github.com/splitbrain/dokuwiki.git

echo "#################################"
echo "#downloaden custom-built dokuwiki scripts #"
echo "#################################"

cd /var/www/html/dokuwiki/bin
git clone https://github.com/kveys/dokuwiki.git 
mv dokuwiki/namespace.sh ..

echo "##########################"
echo "#setting permissions to nginx user #"
echo "##########################"

chown -R "www-data:www-data" /var/www/html/dokuwiki/
chmod -R 755 /var/www/html/dokuwiki/ 

echo "#############################"
echo "#copying & enabling Nginx host config #"
echo "#############################"

mv /var/www/html/dokuwiki/bin/dokuwiki/nginx_location_config /etc/nginx/sites-available/dokuwiki 

ln -s /etc/nginx/sites-available/dokuwiki /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

echo "###############"
echo "#Nginx herstarten  #"
echo "###############"

systemctl restart nginx
